### PR TITLE
Fixes #5 - check for API errors and raise exception if encountered

### LINKED ISSUE #5: Handle error in upsert_timeboard
I tried creating a graph that had an incorrect graph definition. The traceback wasn't helpful at all:

```
 INFO API: Upserting timeboard: circleci-builder-dev
Found 198 existing timeboards in DataDog
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/home/jantman/manheim/git/Tooling/terraform-circleci-builder/vendor/ruby/2.1.0/gems/dogtrainer-0.2.0/lib/dogtrainer/api.rb:531:in `upsert_timeboard'
/home/jantman/manheim/git/Tooling/terraform-circleci-builder/lib/datadog_helpers.rb:149:in `setup_dashboard'
/home/jantman/manheim/git/Tooling/terraform-circleci-builder/Rakefile:79:in `block in <top (required)>'
Tasks: TOP => datadog
(See full trace by running task with --trace)
```

It turns out that DataDog's API returned a 400, but dogapi doesn't treat this as an error, it just returns a normal array; ``@dog.create_dashboard()`` returns:

```
["400", {"errors"=>["Error(s) found in query:\nError parsing query: \n avg:circlecienterprise.circlerunqueuebuilds\n                                           ^\nExpected \"{\" (at char 43), (line:1, col:44) "]}]
```

### PR DESCRIPTION
**Pull request by jantman**
When using this gem in a new project, I tried to create some graphs with an invalid graph definition... and found that I was getting a key error trying to read the result. It turns out that the methods to mute and unmute monitors, and create timeboards and screenboards, weren't checking for API errors.

I added a new custom exception class for API errors, and these methods now raise that if they get an error response.

### CODE REVIEW

File: lib/dogtrainer/api.rb [hunk 1]
```diff
@@ -303,7 +320,7 @@ def upsert_monitor(
 
     # Create a monitor that doesn't already exist; return its id
     #
-    # @param mon_name [String] mane of the monitor to create
+    # @param _mon_name [String] mane of the monitor to create
```
Comment (jniesen) [inline lib/dogtrainer/api.rb:323]: This documented params doesn't seem to be used anywhere. Was it deprecated at some point?

**Review by jniesen — COMMENTED** [review]
Just one question.

**Comment by jniesen** [comment]
:shipit:

File: lib/dogtrainer/api.rb (hunk 1 above)
Comment (jantman) [reply lib/dogtrainer/api.rb:323]: Honestly I don't know... all I know is that when I went to build docs, I got a warning for the param name in the docstring not matching the actual param name on the method, so I fixed the docstring...
